name: Deploy ML API to HuggingFace

on:
  push:
    branches: [ main ]

jobs:

  # ======================
  # 1 TEST
  # ======================
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check FastAPI loads
        run: |
          python -c "import sys; sys.path.insert(0,'.'); from app.main import app; print('API loads successfully')"

  # ======================
  # 2 DEPLOY
  # ======================
  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Deploy to HuggingFace Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          echo "ðŸš€ Deploying to HuggingFace..."

          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

          git clone https://huggingface.co/spaces/amely188/ml-futurisys hf-space
          cd hf-space

          rm -rf * || true

          cp -r ../app .
          cp ../requirements.txt .
          cp ../Dockerfile .
          cp ../README.md .

          git add .
          git commit -m "Auto deploy: ${{ github.sha }}" || exit 0
          git push https://amely188:$HF_TOKEN@huggingface.co/spaces/amely188/ml-futurisys main